name: simple_model
description: "Simple way for converting to and from JSON without code generator."
version: 1.0.7
homepage: https://github.com/davidchow24/simple_model

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.18.0
  meta: ^1.15.0
