name: simple_model
description: "Simple way for converting to and from JSON without code generator."
version: 1.1.0
homepage: https://github.com/davidchow24/simple_model

environment:
  sdk: ">=3.0.0 <4.0.0"

